Readme.md/stilizovanje
udomiljubimca/udomiljubimca-register-api pull request #31
Opened 2021-05-02 13:04 UTC by mifa43

2021-05-02 13:48 UTC, ognjen-it requested changes
Obrisi sve sem readme md file-a

2021-05-02 13:48 UTC, ognjen-it commented on register-api/requirements.txt
> +typing == 3.7.4.3
Ovo je za pravna lica, brsi ovo.

2021-05-02 13:48 UTC, ognjen-it commented on register-api/src/create_association.py
> +from keycloak import KeycloakOpenID
Ovo je za pravna lica, brsi ovo.

2021-05-02 13:48 UTC, ognjen-it commented on register-api/src/docs.py
> +        "description" : "Ova  ruta kreira usera za udruzenja na keycloak-u takodje ima proveru da li udruzenje postoji(username, email)."
Ovo je za pravna lica, brsi ovo.

2021-05-02 13:48 UTC, ognjen-it commented on register-api/src/main.py
> +from create_association import CreateAssociation
Ovo je za pravna lica, brsi ovo.

2021-05-02 13:53 UTC, mifa43 commented
obrisano je

2021-05-02 13:55 UTC, ognjen-it approved these changes

2021-05-03 10:25 UTC, closed without merging

2021-05-21 12:18 UTC, ognjen-it reviewed
.

2021-05-21 12:18 UTC, ognjen-it commented on register-api/src/main.py
> -import logging
Vrati ovo sto ti je izbrisa o tj crveno.

2021-05-21 12:18 UTC, ognjen-it commented on register-api/src/docs.py
> -    {
Vrati ovo sto ti je izbrisa o tj crveno.

2021-05-21 12:18 UTC, ognjen-it commented on register-api/requirements.txt
> -PyJWT==1.7.1
Vrati ovo sto ti je izbrisa o tj crveno.