izmena breisanje reda
udomiljubimca/udomiljubimca-register-api pull request #43
Opened 2021-05-14 12:25 UTC by mifa43

2021-05-14 14:35 UTC, mifa43 commented
Nisam kreirao pull request za udruzenja_role.
Ja sam kreirao role u klijentu app da li je to ono na sta si mislio?

2021-05-15 20:23 UTC, ognjen-it requested changes

2021-05-15 20:23 UTC, ognjen-it commented on register-api/src/main.py
> +            CreateUser(item.email, item.username, item.firstName, item.lastName, item.secret).create_keycloak_roles()
Ako ovo ovako ostavis, to znaci da ce prilikom svakog kreiranja user-a da se opali komanda da kreira user_role, sto zapravo nema nikakvog smisla.
Tako da, na ovom mestu ne treba da se poziva definicija CreateUser nego AssingRole, tj dodeljivanje vec postojece role.

2021-05-15 20:23 UTC, ognjen-it commented on register-api/src/createuser.py
> +        add_role = keycloak_admin.assign_client_role(user_id, client_id,[{'id' : role_id, 'name':'user_role'}])
Ovo sacuvaj i izbrisi jer cemo to koristiti za integracione job-ove prilikom prebacivanje sa develop evironment-a na test i tako dalje..

2021-05-16 10:24 UTC, ognjen-it approved these changes

2021-05-16 10:26 UTC, merged